{ pkgs, inputs, ... }:
{
  home.packages = with pkgs; [
    inputs.opencode-go-usage-analyzer.packages.${pkgs.stdenv.hostPlatform.system}.default
    (inputs.quickshell.packages.${pkgs.stdenv.hostPlatform.system}.default.withModules [
      pkgs.qt6.qtmultimedia
      pkgs.qt6.qtsvg
      pkgs.qt6.qtimageformats
      pkgs.qt6.qtmultimedia
      pkgs.qt6.qt5compat
    ])
    brightnessctl
    sshfs
    file-roller
    zathura
    p7zip
    cliphist
    cloudflared
    deno
    deploy-rs
    fladder
    google-chrome
    hunspell
    hunspellDicts.en_US
    hunspellDicts.pt_PT
    hyprpicker
    jetbrains.datagrip
    libnotify
    libreoffice-qt
    openvpn
    platformio
    rquickshare
    solaar
    sops
    supertuxkart
    tldr
    wl-clipboard
    wrangler
    xdg-utils
  ];
}
