{ pkgs, inputs, ... }:
{
  home.packages = with pkgs; [
    inputs.opencode-go-usage-analyzer.packages.${pkgs.stdenv.hostPlatform.system}.default
    brightnessctl
    sshfs
    file-roller
    zathura
    p7zip
    cliphist
    cloudflared
    deno
    deploy-rs
    fladder
    google-chrome
    hunspell
    hunspellDicts.en_US
    hunspellDicts.pt_PT
    hyprpicker
    jetbrains.datagrip
    jq
    libnotify
    libreoffice-qt
    openvpn
    rquickshare
    solaar
    omp
    sops
    tldr
    wl-clipboard
    wrangler
    xdg-utils
  ];
}
